name: Backend Fly Deploy

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy backend to Fly
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
