name: backend-test

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-test.yml"
    branches:
      - main
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-test.yml"

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"

      - run: gleam deps download
        working-directory: backend

      # - run: gleam test

      - run: gleam check
        working-directory: backend

      - run: gleam format --check src
        working-directory: backend
